import { Document } from '@/interfaces/document';

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    title: 'Blood Test Results',
    timestamp: '12.03.2026',
    size: '425kb',
    type: 'pdf',
    tags: ['Lab Result', 'Blood Test'],
    fileName: 'blood_test_results.pdf',
    status: 'Analyzed',
    fromDate: '10.03.2026',
    uploadedDate: '24.03.2026',
    facilityName: 'City Hospital',
    pages: [
      { id: '1-1', pageNumber: 1 },
      { id: '1-2', pageNumber: 2 },
      { id: '1-3', pageNumber: 3 },
      { id: '1-4', pageNumber: 4 },
    ],
  },
  {
    id: '2',
    title: 'MRI Scan Report',
    timestamp: '05.02.2026',
    size: '1.2mb',
    type: 'pdf',
    tags: ['Medical Report', 'MRI'],
    fileName: 'mri_scan_report.pdf',
    status: 'Pending Review',
    fromDate: '03.02.2026',
    uploadedDate: '05.02.2026',
    facilityName: 'Central Clinic',
    pages: [
      { id: '2-1', pageNumber: 1 },
      { id: '2-2', pageNumber: 2 },
      { id: '2-3', pageNumber: 3 },
    ],
  },
  {
    id: '3',
    title: 'Prescription - Dr. Smith',
    timestamp: '20.01.2026',
    size: '150kb',
    type: 'pdf',
    tags: ['Prescription', 'Demotag'],
    fileName: 'prescription_dr_smith.pdf',
    status: 'Pending Review',
    fromDate: '15.01.2026',
    uploadedDate: '20.01.2026',
    facilityName: 'General Practice',
    pages: [{ id: '3-1', pageNumber: 1 }],
  },
  {
    id: '4',
    title: 'X-Ray Chest Analysis',
    timestamp: '15.12.2025',
    size: '980kb',
    type: 'pdf',
    tags: ['Medical Report', 'X-Ray'],
    fileName: 'x_ray_chest_analysis.pdf',
    status: 'Analyzed',
    fromDate: '10.12.2025',
    uploadedDate: '15.12.2025',
    facilityName: 'City Hospital',
    pages: [
      { id: '4-1', pageNumber: 1 },
      { id: '4-2', pageNumber: 2 },
    ],
  },
  {
    id: '5',
    title: 'Test Summary',
    timestamp: '03.11.2025',
    size: '310kb',
    type: 'pdf',
    tags: ['Lab Result', 'Test'],
    fileName: 'test_summary.pdf',
    status: 'Analyzed',
    fromDate: '01.11.2025',
    uploadedDate: '03.11.2025',
    facilityName: 'Central Clinic',
    pages: [
      { id: '5-1', pageNumber: 1 },
      { id: '5-2', pageNumber: 2 },
      { id: '5-3', pageNumber: 3 },
    ],
  },
  {
    id: '6',
    title: 'Vaccination Certificate',
    timestamp: '27.10.2025',
    size: '205kb',
    type: 'pdf',
    tags: ['Certificate', 'Vaccination'],
    fileName: 'vaccination_certificate.pdf',
    status: 'Analyzed',
    fromDate: '25.10.2025',
    uploadedDate: '27.10.2025',
    facilityName: 'Health Center',
    pages: [
      { id: '6-1', pageNumber: 1 },
      { id: '6-2', pageNumber: 2 },
    ],
  },
];
