"""
User retrieval pipeline.

Two entry points:
  run_retrieval()  — retrieve facts + entities from Graphiti → RetrievalOutput
  run_qa()         — full pipeline: retrieval → Gemini answer → QAOutput

Typical usage:

    # Full QA pipeline (recommended)
    from retrieval.pipeline import run_qa
    result = await run_qa("What medications is this patient on?", user_id="patient_001")
    print(result.answer)

    # Retrieval only (inspect raw facts before answering)
    from retrieval.pipeline import run_retrieval
    out = await run_retrieval("PSA levels", user_id="patient_001")
    print(out.context)

num_results defaults to 4: graph-based facts are much denser than text
chunks, so 4 well-ranked facts give the LLM sufficient context without
overwhelming it with noise.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

from graphiti_core import Graphiti
from graphiti_core.edges import EntityEdge
from graphiti_core.nodes import EntityNode

from retrieval.graphiti_client import create_graphiti
from retrieval.retriever import RetrievalResult, build_medical_filter, search_combined

_log = logging.getLogger(__name__)


# ── Output dataclass ──────────────────────────────────────────────────────────

@dataclass
class RetrievalOutput:
    """
    Output of run_retrieval().

    Attributes:
        query:       The original search query.
        user_id:     Firebase UID used to scope the search.
        edges:       Relevant relationship facts (EntityEdge).
        nodes:       Relevant medical entities (EntityNode).
        context:     Human-readable formatted string (for display / debugging).
        total_edges: Number of edges returned.
        total_nodes: Number of nodes returned.
    """

    query: str
    user_id: str
    edges: list[EntityEdge] = field(default_factory=list)
    nodes: list[EntityNode] = field(default_factory=list)
    context: str = ""
    total_edges: int = 0
    total_nodes: int = 0


@dataclass
class QAOutput:
    """
    Output of run_qa() — the full end-to-end pipeline result.

    Attributes:
        query:     The original user question.
        user_id:   Firebase UID of the patient.
        answer:    Natural-language answer generated by Gemini.
        retrieval: The underlying RetrievalOutput (facts + entities used).
    """

    query: str
    user_id: str
    answer: str
    retrieval: RetrievalOutput


# ── Main pipeline entry point ─────────────────────────────────────────────────

async def run_retrieval(
    query: str,
    user_id: str,
    num_results: int = 4,
    entity_types: list[str] | None = None,
    edge_types: list[str] | None = None,
    current_facts_only: bool = False,
    graphiti: Graphiti | None = None,
) -> RetrievalOutput:
    """
    Retrieve facts + entities from the user's Graphiti knowledge graph.

    Args:
        query:             Natural-language question or search term.
        user_id:           Firebase UID — scopes search to this patient only.
        num_results:       Max facts/entities to retrieve (default 4).
                           Graph facts are dense; 4 is enough context for most queries.
        entity_types:      Optional list of medical entity labels to filter nodes.
                           E.g. ["Medication", "Diagnosis", "LabTest"]
        edge_types:        Optional list of relationship types to filter edges.
                           E.g. ["PRESCRIBED", "HAS_DIAGNOSIS"]
        current_facts_only: If True, exclude superseded (expired) facts.
                            Only returns edges where invalid_at is None.
        graphiti:          Optional pre-built Graphiti instance. If None,
                           one is created and closed automatically.

    Returns:
        RetrievalOutput with edges, nodes, and a formatted context string.
    """
    _log.info("retrieval_start query=%r user_id=%s", query, user_id)

    # Manage Graphiti lifecycle if not provided externally
    _owns_graphiti = graphiti is None
    if _owns_graphiti:
        graphiti = await create_graphiti(build_indices=False)

    try:
        search_filter = build_medical_filter(
            entity_types=entity_types,
            edge_types=edge_types,
        )

        result: RetrievalResult = await search_combined(
            graphiti=graphiti,
            query=query,
            user_id=user_id,
            num_results=num_results,
            search_filter=search_filter,
        )

        edges = result.edges
        nodes = result.nodes

        # Filter to current (non-expired) facts if requested
        if current_facts_only:
            edges = [e for e in edges if e.invalid_at is None]
            _log.info("current_facts_only: filtered to %d edges", len(edges))

        context = _format_context(query=query, user_id=user_id, edges=edges, nodes=nodes)

        output = RetrievalOutput(
            query=query,
            user_id=user_id,
            edges=edges,
            nodes=nodes,
            context=context,
            total_edges=len(edges),
            total_nodes=len(nodes),
        )

        _log.info(
            "retrieval_done user_id=%s edges=%d nodes=%d",
            user_id, len(edges), len(nodes),
        )
        return output

    finally:
        if _owns_graphiti:
            await graphiti.close()


# ── Full QA pipeline ──────────────────────────────────────────────────────────

async def run_qa(
    query: str,
    user_id: str,
    num_results: int = 4,
    entity_types: list[str] | None = None,
    edge_types: list[str] | None = None,
    current_facts_only: bool = False,
    graphiti: Graphiti | None = None,
) -> QAOutput:
    """
    Full end-to-end pipeline: query → retrieve graph facts → Gemini answer.

    Step 1 — Graphiti retrieval:
        Search the user's knowledge graph for facts (EntityEdge) and entities
        (EntityNode) most relevant to the query. Uses hybrid semantic+BM25
        search with cross-encoder reranking, scoped to group_id=user_id.

    Step 2 — LLM answering (Gemini via Vertex AI):
        Format the retrieved facts into a structured prompt and send to Gemini
        2.5 Flash. The LLM synthesises the temporal, relationship-aware graph
        facts into a clear natural-language answer.

    This is graph-RAG: the LLM reasons over structured facts rather than raw
    text chunks, which gives more precise, temporally-aware medical answers
    with less hallucination risk.

    Args:
        query:             Natural-language question (e.g. "What medications?").
        user_id:           Firebase UID of the patient to query.
        num_results:       Max facts/entities retrieved (default 4).
        entity_types:      Optional entity label filter (e.g. ["Medication"]).
        edge_types:        Optional relationship type filter (e.g. ["PRESCRIBED"]).
        current_facts_only: If True, exclude expired/superseded facts.
        graphiti:          Optional pre-built Graphiti instance.

    Returns:
        QAOutput with answer (str) and the underlying RetrievalOutput.
    """
    # Import here to avoid circular import at module level
    from retrieval.answerer import generate_answer

    _log.info("run_qa start query=%r user_id=%s", query, user_id)

    # Step 1: retrieve
    retrieval = await run_retrieval(
        query=query,
        user_id=user_id,
        num_results=num_results,
        entity_types=entity_types,
        edge_types=edge_types,
        current_facts_only=current_facts_only,
        graphiti=graphiti,
    )

    # Step 2: answer
    answer = await generate_answer(query=query, retrieval=retrieval)

    _log.info(
        "run_qa done user_id=%s answer_len=%d",
        user_id, len(answer),
    )

    return QAOutput(
        query=query,
        user_id=user_id,
        answer=answer,
        retrieval=retrieval,
    )


# ── Context formatter ─────────────────────────────────────────────────────────

def _format_context(
    query: str,
    user_id: str,
    edges: list[EntityEdge],
    nodes: list[EntityNode],
) -> str:
    """
    Format retrieval results into a structured context string for LLM prompts.

    Sections:
      - Header with query + user
      - Relevant Facts (edges): relationship type, fact text, valid/invalid dates
      - Relevant Entities (nodes): entity type, name, summary
    """
    lines: list[str] = []

    lines.append("=" * 60)
    lines.append("PATIENT KNOWLEDGE GRAPH — RETRIEVAL CONTEXT")
    lines.append("=" * 60)
    lines.append(f"User ID : {user_id}")
    lines.append(f"Query   : {query}")
    lines.append(f"Results : {len(edges)} facts, {len(nodes)} entities")
    lines.append("")

    # ── Facts (edges) ─────────────────────────────────────────────────────────
    if edges:
        lines.append(f"--- RELEVANT FACTS ({len(edges)}) ---")
        for i, edge in enumerate(edges, start=1):
            lines.append(f"\n[{i}] {edge.name}")
            lines.append(f"    Fact   : {edge.fact}")

            valid_str   = _fmt_date(edge.valid_at)
            invalid_str = _fmt_date(edge.invalid_at) if edge.invalid_at else "current"
            lines.append(f"    Period : {valid_str} → {invalid_str}")

        lines.append("")
    else:
        lines.append("--- RELEVANT FACTS ---")
        lines.append("No facts found for this query.")
        lines.append("")

    # ── Entities (nodes) ──────────────────────────────────────────────────────
    if nodes:
        lines.append(f"--- RELEVANT ENTITIES ({len(nodes)}) ---")
        for i, node in enumerate(nodes, start=1):
            labels = ", ".join(node.labels) if node.labels else "Entity"
            lines.append(f"\n[{i}] [{labels}] {node.name}")
            if node.summary:
                lines.append(f"    Summary: {node.summary}")
    else:
        lines.append("--- RELEVANT ENTITIES ---")
        lines.append("No entities found for this query.")

    lines.append("")
    lines.append("=" * 60)

    return "\n".join(lines)


def _fmt_date(dt: datetime | None) -> str:
    if dt is None:
        return "unknown"
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%Y-%m-%d")
